"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# Midtrans API Configuration
MIDTRANS_SERVER_KEY = "SB-Mid-server-ZfMHWNkATrl67axhr8Mm5O43"
MIDTRANS_CLIENT_KEY = "SB-Mid-client-DGBwaCpUGKwrhEkH"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z+ksf@)0d^qojbh4rnp4b1to$hq&*tt(3bs$gf(3i267g$k9ln'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'store.apps.StoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/images/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
# Midtrans API Credentials
MIDTRANS_MERCHANT_ID = 'G465704747'
MIDTRANS_CLIENT_KEY = 'Mid-client-UXuBlTRfxBh8PUfC'
MIDTRANS_SERVER_KEY = 'Mid-server-hmm8a4bevYUybOzH5x-MvIDX'

# Midtrans Configuration
MIDTRANS_SERVER_KEY = 'Mid-server-hmm8a4bevYUybOzH5x-MvIDX'
MIDTRANS_CLIENT_KEY = 'Mid-client-UXuBITRfxBh8PUfC'
MIDTRANS_BASE_URL = 'https://app.sandbox.midtrans.com/snap/v1/transactions'

# Midtrans Configuration
MIDTRANS_SERVER_KEY = 'Mid-server-your-server-key'
MIDTRANS_CLIENT_KEY = 'Mid-client-your-client-key'
MIDTRANS_IS_PRODUCTION = False  # Set to True in production

# Midtrans Configuration
MIDTRANS_SERVER_KEY = 'Mid-server-your-server-key'
MIDTRANS_CLIENT_KEY = 'Mid-client-your-client-key'
MIDTRANS_IS_PRODUCTION = False  # Set True for production

# Midtrans Configuration
MIDTRANS_SERVER_KEY = 'Mid-server-your-server-key'
MIDTRANS_CLIENT_KEY = 'Mid-client-your-client-key'
MIDTRANS_IS_PRODUCTION = False  # Change to True for production
